In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix
from nltk.translate.bleu_score import corpus_bleu

# Sample data for analysis
sentiment_labels = ['positive', 'negative', 'neutral']
true_sentiments = ['positive', 'negative', 'neutral', 'positive', 'neutral']
predicted_sentiments = ['positive', 'neutral', 'negative', 'negative', 'neutral']

intents = ['greeting', 'farewell', 'question', 'feedback']
true_intents = ['greeting', 'question', 'farewell', 'question', 'feedback']
predicted_intents = ['greeting', 'farewell', 'question', 'farewell', 'feedback']

reference_responses = [['Hello!', 'Hi there!'], ['Goodbye!', 'See you later!']]
generated_responses = [['Hello!', 'Hey!'], ['Bye!', 'Goodbye!']]

emotions = ['happy', 'sad', 'angry']
true_emotions = ['happy', 'sad', 'angry', 'happy', 'sad']
predicted_emotions = ['happy', 'sad', 'happy', 'angry', 'angry']

# Sentiment Analysis Results and Analysis
print("Sentiment Analysis Results:")
print(classification_report(true_sentiments, predicted_sentiments, target_names=sentiment_labels))
print("Confusion Matrix:")
print(confusion_matrix(true_sentiments, predicted_sentiments, labels=sentiment_labels))

# Intent Recognition Results and Analysis
print("\nIntent Recognition Results:")
print(classification_report(true_intents, predicted_intents, target_names=intents))
print("Confusion Matrix:")
print(confusion_matrix(true_intents, predicted_intents, labels=intents))

# Language Generation Results and Analysis
print("\nLanguage Generation Results:")
print("BLEU Score:", corpus_bleu(reference_responses, generated_responses))

# Emotion Understanding Results and Analysis
print("\nEmotion Understanding Results:")
print(classification_report(true_emotions, predicted_emotions, target_names=emotions))
print("Confusion Matrix:")
print(confusion_matrix(true_emotions, predicted_emotions, labels=emotions))


Sentiment Analysis Results:
              precision    recall  f1-score   support

    positive       0.00      0.00      0.00         1
    negative       0.50      0.50      0.50         2
     neutral       1.00      0.50      0.67         2

    accuracy                           0.40         5
   macro avg       0.50      0.33      0.39         5
weighted avg       0.60      0.40      0.47         5

Confusion Matrix:
[[1 1 0]
 [0 0 1]
 [0 1 1]]

Intent Recognition Results:
              precision    recall  f1-score   support

    greeting       0.00      0.00      0.00         1
    farewell       1.00      1.00      1.00         1
    question       1.00      1.00      1.00         1
    feedback       0.00      0.00      0.00         2

    accuracy                           0.40         5
   macro avg       0.50      0.50      0.50         5
weighted avg       0.40      0.40      0.40         5

Confusion Matrix:
[[1 0 0 0]
 [0 0 1 0]
 [0 2 0 0]
 [0 0 0 1]]

Language Generati

In [2]:
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
from ipywidgets import interact, fixed

# Sample data for analysis
sentiment_labels = ['positive', 'negative', 'neutral']
true_sentiments = ['positive', 'negative', 'neutral', 'positive', 'neutral']
predicted_sentiments = ['positive', 'neutral', 'negative', 'negative', 'neutral']

# Function to plot confusion matrix
def plot_confusion_matrix(true_labels, predicted_labels, labels):
    cm = confusion_matrix(true_labels, predicted_labels, labels=labels)
    cm_df = pd.DataFrame(cm, index=labels, columns=labels)
    plt.figure(figsize=(8, 6))
    plt.imshow(cm_df, interpolation='nearest', cmap=plt.cm.Blues)
    plt.title('Confusion Matrix')
    plt.colorbar()
    tick_marks = np.arange(len(labels))
    plt.xticks(tick_marks, labels, rotation=45)
    plt.yticks(tick_marks, labels)
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label')
    plt.tight_layout()
    plt.show()

# Interactive confusion matrix plot
interact(plot_confusion_matrix, true_labels=fixed(true_sentiments), predicted_labels=fixed(predicted_sentiments), labels=fixed(sentiment_labels))


interactive(children=(Output(),), _dom_classes=('widget-interact',))

<function __main__.plot_confusion_matrix(true_labels, predicted_labels, labels)>

In [3]:
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt

# Function to plot confusion matrix
def plot_confusion_matrix(true_labels, predicted_labels, labels):
    cm = confusion_matrix(true_labels, predicted_labels, labels=labels)
    cm_df = pd.DataFrame(cm, index=labels, columns=labels)
    plt.figure(figsize=(8, 6))
    plt.imshow(cm_df, interpolation='nearest', cmap=plt.cm.Blues)
    plt.title('Confusion Matrix')
    plt.colorbar()
    tick_marks = np.arange(len(labels))
    plt.xticks(tick_marks, labels, rotation=45)
    plt.yticks(tick_marks, labels)
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label')
    plt.tight_layout()
    plt.show()

# Sample data for analysis
sentiment_labels = ['positive', 'negative', 'neutral']
intents = ['greeting', 'farewell', 'question', 'feedback']
emotions = ['happy', 'sad', 'angry']

# Function to interactively analyze user input
def analyze_user_input():
    print("Bot: Hi there! Let's have a conversation.")
    print("Bot: How are you feeling today?")
    user_sentiment = input("You: ")

    if user_sentiment.lower() not in sentiment_labels:
        print("Bot: I'm sorry, I didn't understand that sentiment.")
        return

    print("Bot: What's on your mind? Are you asking a question, giving feedback, saying goodbye, or something else?")
    user_intent = input("You: ")

    if user_intent.lower() not in intents:
        print("Bot: I'm sorry, I couldn't identify your intent.")
        return

    print("Bot: Can you tell me how you're feeling right now? Are you happy, sad, angry, or something else?")
    user_emotion = input("You: ")

    if user_emotion.lower() not in emotions:
        print("Bot: I'm sorry, I couldn't understand your emotion.")
        return

    # Perform analysis based on user input
    print("\nBot: Let me analyze your responses...")
    print("--------------------------------------------------")

    print("\nSentiment Analysis Results:")
    print(f"User Sentiment: {user_sentiment}")
    # Additional analysis steps for sentiment

    print("\nIntent Recognition Results:")
    print(f"User Intent: {user_intent}")
    # Additional analysis steps for intent

    print("\nEmotion Understanding Results:")
    print(f"User Emotion: {user_emotion}")
    # Additional analysis steps for emotion

    # Plot confusion matrices
    plot_confusion_matrix([user_sentiment], [user_sentiment], sentiment_labels)
    plot_confusion_matrix([user_intent], [user_intent], intents)
    plot_confusion_matrix([user_emotion], [user_emotion], emotions)

# Interactive conversation loop
while True:
    analyze_user_input()
    continue_option = input("Bot: Do you want to continue our conversation? (yes/no): ")
    if continue_option.lower() != 'yes':
        print("Bot: Okay, goodbye!")
        break


Bot: Hi there! Let's have a conversation.
Bot: How are you feeling today?
You: sad
Bot: I'm sorry, I didn't understand that sentiment.
Bot: Do you want to continue our conversation? (yes/no): no
Bot: Okay, goodbye!


In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

nltk.download('vader_lexicon')

# Function to plot confusion matrix
def plot_confusion_matrix(true_labels, predicted_labels, labels):
    cm = confusion_matrix(true_labels, predicted_labels, labels=labels)
    cm_df = pd.DataFrame(cm, index=labels, columns=labels)
    plt.figure(figsize=(8, 6))
    plt.imshow(cm_df, interpolation='nearest', cmap=plt.cm.Blues)
    plt.title('Confusion Matrix')
    plt.colorbar()
    tick_marks = np.arange(len(labels))
    plt.xticks(tick_marks, labels, rotation=45)
    plt.yticks(tick_marks, labels)
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label')
    plt.tight_layout()
    plt.show()

# Sample data for analysis
sentiment_labels = ['positive', 'negative', 'neutral']
intents = ['greeting', 'farewell', 'question', 'feedback']
emotions = ['happy', 'sad', 'angry']

# Function to analyze user input and judge mood
def analyze_user_input(user_input):
    response = None

    if "help" in user_input.lower() and "academics" in user_input.lower():
        response = "Sure! What specific academic assistance do you need?"

    elif "academics" in user_input.lower() and "struggling" in user_input.lower():
        response = "I'm sorry to hear that. It's important to ask for help when you need it. Can you tell me more about what you're struggling with?"

    elif "thank" in user_input.lower():
        response = "You're welcome! If you need further assistance, feel free to ask."

    else:
        print("Bot: I'm sorry, I'm currently focused on analyzing sentiments, intents, and emotions. Can we continue with that?")

    # Judge user's mood
    sid = SentimentIntensityAnalyzer()
    compound_score = sid.polarity_scores(user_input)['compound']

    if compound_score >= 0.05:
        mood = "positive"
    elif compound_score <= -0.05:
        mood = "negative"
    else:
        mood = "neutral"

    return response, mood

# Interactive conversation loop
def start_conversation():
    print("Bot: Hi there! I'm ChatBot. What's your name?")
    user_name = input("You: ")
    print(f"Bot: Nice to meet you, {user_name}!")
    print("Bot: How can I assist you today?")

    while True:
        user_input = input("You: ")

        if user_input.lower() in ['no', 'exit', 'bye', 'goodbye']:
            print("Bot: Okay, goodbye!")
            break

        response, mood = analyze_user_input(user_input)

        if response:
            print(f"Bot: {response}")
        else:
            print("Bot: I'm glad you're interested in chatting more! Let's continue exploring sentiments, intents, and emotions.")

        print(f"Bot: Your mood seems {mood} based on your input.")

start_conversation()


[nltk_data] Downloading package vader_lexicon to /root/nltk_data...


Bot: Hi there! I'm ChatBot. What's your name?


In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

nltk.download('vader_lexicon')

# Function to plot confusion matrix
def plot_confusion_matrix(true_labels, predicted_labels, labels):
    cm = confusion_matrix(true_labels, predicted_labels, labels=labels)
    cm_df = pd.DataFrame(cm, index=labels, columns=labels)
    plt.figure(figsize=(8, 6))
    plt.imshow(cm_df, interpolation='nearest', cmap=plt.cm.Blues)
    plt.title('Confusion Matrix')
    plt.colorbar()
    tick_marks = np.arange(len(labels))
    plt.xticks(tick_marks, labels, rotation=45)
    plt.yticks(tick_marks, labels)
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label')
    plt.tight_layout()
    plt.show()

# Sample data for analysis
sentiment_labels = ['positive', 'negative', 'neutral']
intents = ['greeting', 'farewell', 'question', 'feedback']
emotions = ['happy', 'sad', 'angry']

# Function to analyze user input and judge mood
def analyze_user_input(user_input, true_sentiment, true_intent, true_emotion):
    response = None

    if "help" in user_input.lower() and "academics" in user_input.lower():
        response = "Sure! What specific academic assistance do you need?"

    elif "academics" in user_input.lower() and "struggling" in user_input.lower():
        response = "I'm sorry to hear that. It's important to ask for help when you need it. Can you tell me more about what you're struggling with?"

    elif "thank" in user_input.lower():
        response = "You're welcome! If you need further assistance, feel free to ask."

    else:
        print("Bot: I'm sorry, I'm currently focused on analyzing sentiments, intents, and emotions. Can we continue with that?")

    # Judge user's mood
    sid = SentimentIntensityAnalyzer()
    compound_score = sid.polarity_scores(user_input)['compound']

    if compound_score >= 0.05:
        mood = "positive"
    elif compound_score <= -0.05:
        mood = "negative"
    else:
        mood = "neutral"

    # Evaluate performance
    predicted_sentiment = "neutral"  # Placeholder for demonstration
    predicted_intent = "question"  # Placeholder for demonstration
    predicted_emotion = "neutral"  # Placeholder for demonstration

    print("\nPerformance Evaluation:")
    print("Sentiment Classification Report:")
    print(classification_report([true_sentiment], [predicted_sentiment], labels=sentiment_labels))

    print("\nIntent Classification Report:")
    print(classification_report([true_intent], [predicted_intent], labels=intents))

    print("\nEmotion Classification Report:")
    print(classification_report([true_emotion], [predicted_emotion], labels=emotions))

    # Plot confusion matrices
    plot_confusion_matrix([true_sentiment], [predicted_sentiment], labels=sentiment_labels)
    plot_confusion_matrix([true_intent], [predicted_intent], labels=intents)
    plot_confusion_matrix([true_emotion], [predicted_emotion], labels=emotions)

    return response, mood

# Interactive conversation loop
def start_conversation():
    print("Bot: Hi there! I'm ChatBot. What's your name?")
    user_name = input("You: ")
    print(f"Bot: Nice to meet you, {user_name}!")
    print("Bot: How can I assist you today?")

    while True:
        user_input = input("You: ")

        if user_input.lower() in ['no', 'exit', 'bye', 'goodbye']:
            print("Bot: Okay, goodbye!")
            break

        # Manually define true labels for demonstration
        true_sentiment = "neutral"
        true_intent = "question"
        true_emotion = "neutral"

        response, mood = analyze_user_input(user_input, true_sentiment, true_intent, true_emotion)

        if response:
            print(f"Bot: {response}")
        else:
            print("Bot: I'm glad you're interested in chatting more! Let's continue exploring sentiments, intents, and emotions.")

        print(f"Bot: Your mood seems {mood} based on your input.")

start_conversation()


In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

nltk.download('vader_lexicon')

# Function to plot confusion matrix
def plot_confusion_matrix(true_labels, predicted_labels, labels):
    cm = confusion_matrix(true_labels, predicted_labels, labels=labels)
    cm_df = pd.DataFrame(cm, index=labels, columns=labels)
    plt.figure(figsize=(8, 6))
    plt.imshow(cm_df, interpolation='nearest', cmap=plt.cm.Blues)
    plt.title('Confusion Matrix')
    plt.colorbar()
    tick_marks = np.arange(len(labels))
    plt.xticks(tick_marks, labels, rotation=45)
    plt.yticks(tick_marks, labels)
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label')
    plt.tight_layout()
    plt.show()

# Sample data for analysis
sentiment_labels = ['positive', 'negative', 'neutral']
intents = ['greeting', 'farewell', 'question', 'feedback']
emotions = ['happy', 'sad', 'angry']

# Function to analyze user input and judge mood
def analyze_user_input(user_input, true_sentiment, true_intent, true_emotion):
    response = None

    if "help" in user_input.lower() and "academics" in user_input.lower():
        response = "Sure! What specific academic assistance do you need?"

    elif "academics" in user_input.lower() and "struggling" in user_input.lower():
        response = "I'm sorry to hear that. It's important to ask for help when you need it. Can you tell me more about what you're struggling with?"

    elif "thank" in user_input.lower():
        response = "You're welcome! If you need further assistance, feel free to ask."

    else:
        print("Bot: I'm sorry, I'm currently focused on analyzing sentiments, intents, and emotions. Can we continue with that?")

    # Judge user's mood
    sid = SentimentIntensityAnalyzer()
    compound_score = sid.polarity_scores(user_input)['compound']

    if compound_score >= 0.05:
        mood = "positive"
    elif compound_score <= -0.05:
        mood = "negative"
    else:
        mood = "neutral"

    # Evaluate performance
    predicted_sentiment = "neutral"  # Placeholder for demonstration
    predicted_intent = "question"  # Placeholder for demonstration
    predicted_emotion = "neutral"  # Placeholder for demonstration

    sentiment_accuracy = 1 if true_sentiment == predicted_sentiment else 0
    intent_accuracy = 1 if true_intent == predicted_intent else 0
    emotion_accuracy = 1 if true_emotion == predicted_emotion else 0

    return response, mood, sentiment_accuracy, intent_accuracy, emotion_accuracy

# Interactive conversation loop
def start_conversation():
    print("Bot: Hi there! I'm ChatBot. What's your name?")
    user_name = input("You: ")
    print(f"Bot: Nice to meet you, {user_name}!")
    print("Bot: How can I assist you today?")

    # Manually define true labels for demonstration
    true_sentiment = "neutral"
    true_intent = "question"
    true_emotion = "neutral"

    total_samples = 0
    correct_sentiment_predictions = 0
    correct_intent_predictions = 0
    correct_emotion_predictions = 0

    while True:
        user_input = input("You: ")

        if user_input.lower() in ['no', 'exit', 'bye', 'goodbye']:
            print("Bot: Okay, goodbye!")
            break

        total_samples += 1

        response, mood, sentiment_accuracy, intent_accuracy, emotion_accuracy = analyze_user_input(user_input, true_sentiment, true_intent, true_emotion)

        correct_sentiment_predictions += sentiment_accuracy
        correct_intent_predictions += intent_accuracy
        correct_emotion_predictions += emotion_accuracy

        if response:
            print(f"Bot: {response}")
        else:
            print("Bot: I'm glad you're interested in chatting more! Let's continue exploring sentiments, intents, and emotions.")

        print(f"Bot: Your mood seems {mood} based on your input.")

    # Calculate accuracy
    sentiment_accuracy = correct_sentiment_predictions / total_samples * 100 if total_samples > 0 else 0
    intent_accuracy = correct_intent_predictions / total_samples * 100 if total_samples > 0 else 0
    emotion_accuracy = correct_emotion_predictions / total_samples * 100 if total_samples > 0 else 0

    print("\nPerformance Evaluation:")
    print(f"Sentiment Accuracy: {sentiment_accuracy:.2f}%")
    print(f"Intent Accuracy: {intent_accuracy:.2f}%")
    print(f"Emotion Accuracy: {emotion_accuracy:.2f}%")

start_conversation()


In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

nltk.download('vader_lexicon')

# Function to plot confusion matrix
def plot_confusion_matrix(true_labels, predicted_labels, labels, title):
    cm = confusion_matrix(true_labels, predicted_labels, labels=labels)
    cm_df = pd.DataFrame(cm, index=labels, columns=labels)
    plt.figure(figsize=(8, 6))
    plt.imshow(cm_df, interpolation='nearest', cmap=plt.cm.Blues)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(labels))
    plt.xticks(tick_marks, labels, rotation=45)
    plt.yticks(tick_marks, labels)
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label')
    plt.tight_layout()
    plt.show()

# Sample data for analysis
sentiment_labels = ['positive', 'negative', 'neutral']
intents = ['greeting', 'farewell', 'question', 'feedback']
emotions = ['happy', 'sad', 'angry']

# Function to analyze user input and judge mood
def analyze_user_input(user_input, true_sentiment, true_intent, true_emotion):
    response = None

    if "help" in user_input.lower() and "academics" in user_input.lower():
        response = "Sure! What specific academic assistance do you need?"

    elif "academics" in user_input.lower() and "struggling" in user_input.lower():
        response = "I'm sorry to hear that. It's important to ask for help when you need it. Can you tell me more about what you're struggling with?"

    elif "thank" in user_input.lower():
        response = "You're welcome! If you need further assistance, feel free to ask."

    else:
        print("Bot: I'm sorry, I'm currently focused on analyzing sentiments, intents, and emotions. Can we continue with that?")

    # Judge user's mood
    sid = SentimentIntensityAnalyzer()
    compound_score = sid.polarity_scores(user_input)['compound']

    if compound_score >= 0.05:
        mood = "positive"
    elif compound_score <= -0.05:
        mood = "negative"
    else:
        mood = "neutral"

    # Evaluate performance
    predicted_sentiment = "neutral"  # Placeholder for demonstration
    predicted_intent = "question"  # Placeholder for demonstration
    predicted_emotion = "neutral"  # Placeholder for demonstration

    sentiment_accuracy = 1 if true_sentiment == predicted_sentiment else 0
    intent_accuracy = 1 if true_intent == predicted_intent else 0
    emotion_accuracy = 1 if true_emotion == predicted_emotion else 0

    return response, mood, sentiment_accuracy, intent_accuracy, emotion_accuracy, predicted_sentiment, predicted_intent, predicted_emotion

# Interactive conversation loop
def start_conversation():
    print("Bot: Hi there! I'm ChatBot. What's your name?")
    user_name = input("You: ")
    print(f"Bot: Nice to meet you, {user_name}!")
    print("Bot: How can I assist you today?")

    # Manually define true labels for demonstration
    true_sentiment = "neutral"
    true_intent = "question"
    true_emotion = "neutral"

    total_samples = 0
    correct_sentiment_predictions = 0
    correct_intent_predictions = 0
    correct_emotion_predictions = 0

    predicted_sentiments = []
    predicted_intents = []
    predicted_emotions = []

    while True:
        user_input = input("You: ")

        if user_input.lower() in ['no', 'exit', 'bye', 'goodbye']:
            print("Bot: Okay, goodbye!")
            break

        total_samples += 1

        response, mood, sentiment_accuracy, intent_accuracy, emotion_accuracy, predicted_sentiment, predicted_intent, predicted_emotion = analyze_user_input(user_input, true_sentiment, true_intent, true_emotion)

        correct_sentiment_predictions += sentiment_accuracy
        correct_intent_predictions += intent_accuracy
        correct_emotion_predictions += emotion_accuracy

        predicted_sentiments.append(predicted_sentiment)
        predicted_intents.append(predicted_intent)
        predicted_emotions.append(predicted_emotion)

        if response:
            print(f"Bot: {response}")
        else:
            print("Bot: I'm glad you're interested in chatting more! Let's continue exploring sentiments, intents, and emotions.")

        print(f"Bot: Your mood seems {mood} based on your input.")

    # Calculate accuracy
    sentiment_accuracy = correct_sentiment_predictions / total_samples * 100 if total_samples > 0 else 0
    intent_accuracy = correct_intent_predictions / total_samples * 100 if total_samples > 0 else 0
    emotion_accuracy = correct_emotion_predictions / total_samples * 100 if total_samples > 0 else 0

    print("\nPerformance Evaluation:")
    print(f"Sentiment Accuracy: {sentiment_accuracy:.2f}%")
    print(f"Intent Accuracy: {intent_accuracy:.2f}%")
    print(f"Emotion Accuracy: {emotion_accuracy:.2f}%")

    # Generate confusion matrices
    plot_confusion_matrix([true_sentiment] * total_samples, predicted_sentiments, labels=sentiment_labels, title="Sentiment Confusion Matrix")
    plot_confusion_matrix([true_intent] * total_samples, predicted_intents, labels=intents, title="Intent Confusion Matrix")
    plot_confusion_matrix([true_emotion] * total_samples, predicted_emotions, labels=emotions, title="Emotion Confusion Matrix")

start_conversation()
